### ISSUE TITLE
Unavailable for R version

### ISSUE THREAD

**Issue by M-Schreurs** [tomwenseleers/export#43]
Hi Tom and Christophe,
Your export package is not available for my R version 3.6.1.
Can you make this available, or can you tell me which R version you would recommend instead?
Kind regards!

**Comment by Yingjie4Science** [comment]
same here: 

package ‘export’ is not available (for R version 3.6.1)

**Comment by cvanderaa** [comment]
Apologies for my late reply...I guess you are trying to install `export` using the following command:
```r
install.packages("export")
```
Unfortunately, this is not working because `export` is not on CRAN anymore. I'll try to have it put back again, but I currently can't find the time to do so... (cf issue https://github.com/tomwenseleers/export/issues/41)

You can still install `export` from GitHub:
```r
BiocManager::install("tomwenseleers/export")
```

**Comment by M-Schreurs** [comment]
Hi Christoph, thanks for the help!
I was trying to install using install_github("tomwenseleers/export"), but using BiocManager did the trick.

**Comment by cvanderaa** [comment]
Excellent! I will close the issue for now but I'll work on getting the package on CRAN (what will facilitate installation) as soon as I can find some time! Make sure to follow issue #41 to get updated if interested.

**Comment by tomwenseleers** [comment]
The package is now up an CRAN again and works ok with the latest R version.
